//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fedyaev_Language_01.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientService
    {
        public int ID { get; set; }
        public int IDClient { get; set; }
        public int IDService { get; set; }
        public System.DateTime DateStart { get; set; }
        public string Comment { get; set; }
        public bool IsDone { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
    }
}
