//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fedyaev_Language_01.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePhoto
    {
        public int IDService { get; set; }
        public string PhotoService { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
