//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fedyaev_Language_01.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_ClientList
    {
        public int ID { get; set; }
        public string Gender { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime DateBith { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime DateRegistration { get; set; }
        public Nullable<System.DateTime> DateLastVisit { get; set; }
        public Nullable<int> CountVisit { get; set; }
        public string TagList { get; set; }
        public int IDGender { get; set; }
    }
}
